version: "3.8"

services:
  postgres:
    image: postgres:17.5
    container_name: pg-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: logistics
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - logistics-net

  discovery-service:
    image: discovery-service:0.0.1-SNAPSHOT
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - logistics-net

  booking-service:
    image: booking-service:0.0.1-SNAPSHOT
    container_name: booking-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - logistics-net

  trip-service:
    image: trip-service:0.0.1-SNAPSHOT
    container_name: trip-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - discovery-service
    networks:
      - logistics-net

volumes:
  pg_data:

networks:
  logistics-net:
    # name: logistics-net # if network not created before
    external: true # if net already created before



# podman compose -f logistics-compose.yml up -d
# podman compose -f logistics-compose.yml down
