spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      globalcors:
#        add-to-simple-url-handler-mapping: true  # <- CRITICAL! Without add-to-simple-url-handler-mapping: true, Spring Cloud Gateway won?t actually use your CORS config
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true  # Converts service names to lowercase
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**

        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/api/invoices/**

        - id: stakeholder-service
          uri: lb://stakeholder-service
          predicates:
            - Path=/api/consignees/**, /api/brokers/**, /api/drivers/**
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

