spring:
  application:
    name: stakeholder-service
  datasource:
    url: jdbc:postgresql://pg-db:5432/logistics
    username: user
    password: userpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka