spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics
    username: user
    password: userpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      discovery:
        enabled: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


price:
  perKg: 10